import webbrowser
import os
import subprocess

def main():
    _html = r'''<!doctypehtml><html lang="en"><meta charset="UTF-8"><meta content="width=device-width,initial-scale=1"name="viewport"><style>*{font-family:sans-serif;} div{margin-bottom:10px}.container{display: grid; place-items: center;}.inner{width: 60vw; outline: 6px groove tomato; border-radius: 2vw; outline-offset: 5vh; display: flex; flex-direction: column; align-items: center; margin-top: 5vh;} .info > * { font-size: calc(0.5rem + 0.75vw); padding: 0.3ch 0; } div div h3 {margin-bottom: 12vh;}</style><script>function redirectToPage() { window.location.href = 'http://www.shadowdrums.com'; } async function fetchSystemInfo() { try { const response = await fetch('http://127.0.0.1:5000/system_info'); const data = await response.json(); document.getElementById('cpu_usage').innerText = data.cpu_usage; document.getElementById('ram_usage').innerText = data.ram_usage; document.getElementById('disk_total').innerText = data.disk_total; document.getElementById('disk_used').innerText = data.disk_used; document.getElementById('disk_free').innerText = data.disk_free; document.getElementById('disk_usage').innerText = data.disk_usage; document.getElementById('cpu_temp').innerText = data.cpu_temp !== null ? data.cpu_temp : 'N/A'; document.getElementById('private_ip').innerText = data.private_ip; document.getElementById('public_ip').innerText = data.public_ip; let gpuInfo = ''; data.gpu_info.forEach(gpu => { gpuInfo += `Name: ${gpu.gpu_name}, Load: ${gpu.gpu_load.toFixed(2)}%, Temp: ${gpu.gpu_temperature}°C<br>`; }); document.getElementById('gpu_info').innerHTML = gpuInfo; } catch (error) { console.error('Error fetching system info:', error); } } setInterval(fetchSystemInfo, 5000); fetchSystemInfo();</script><div class="container"><h1 style="font-size:2.5em">Shad's Box O'Stuff</h1><div class="inner"><p>Press OK to continue to the page:</p><button onclick="redirectToPage()">OK</button><h3>Device Info</h3><div class="info"><div>CPU Usage: <span id="cpu_usage"></span>%</div><div>RAM Usage: <span id="ram_usage"></span>%</div><div>Disk Total: <span id="disk_total"></span> GB</div><div>Disk Used: <span id="disk_used"></span> GB</div><div>Disk Free: <span id="disk_free"></span> GB</div><div>Disk Usage: <span id="disk_usage"></span>%</div><div>CPU Temperature: <span id="cpu_temp"></span>°C</div><div>Private IP: <span id="private_ip"></span></div><div>Public IP: <span id="public_ip"></span></div><div>GPU Info: <span id="gpu_info"></span></div></div></div></div>'''
    output_file_path = os.path.join(os.path.dirname(__file__), 'output.html')
    with open(output_file_path, 'w', encoding='utf-8') as file:
        file.write(_html)
    subprocess.Popen(['python', os.path.join(os.path.dirname(__file__), 'backend.py')], cwd=os.path.dirname(__file__))
    webbrowser.open(f'file://{os.path.abspath(output_file_path)}')

if __name__ == "__main__":
        main()